///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013 Tim Leonard
///////////////////////////////////////////////////////////////////////////////	
// Generated by update_version.py
// 24-11-2013 21:36
///////////////////////////////////////////////////////////////////////////////	
// WARNING: Do not modify this file in any way, it's format is assumed by
//			several python scripts used during building!
///////////////////////////////////////////////////////////////////////////////	
#pragma once

#ifndef _Game_VERSION_H_
#define _Game_VERSION_H_

namespace GameAutoVersion
{
	static const char DAY[] = "24";
	static const char MONTH[] = "11";
	static const char YEAR[] = "2013";
	
	static const char HOUR[] = "21";
	static const char MINUTE[] = "36";
	static const char SECOND[] = "14";
	
	static const char STATUS[] = "Alpha";
	static const char STATUS_SHORT[] = "a";

	static const long MAJOR = 1;
	static const long MINOR = 0;
	static const long BUILD = 15.64;
	static const long REVISION = 64;

	static const char FULLVERSION_STRING[] = "1.0.15.64.64a";

	static const long TOTAL_BUILDS = 1564;
}

#endif // _VERSION_H_
